import { User, UserRole } from "@/types";

export const DEMO_USERS: Record<UserRole, User> = {
  CANDIDATE: {
    id: "user-cand-01",
    email: "rohit.sharma@candidate.careeris.in",
    fullName: "Rohit Sharma",
    phone: "+91 98230 12345",
    avatarUrl: "",
    roleType: "CANDIDATE",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2026-01-10T10:00:00Z",
  },
  EMPLOYER: {
    id: "user-emp-01",
    email: "priya.mehta@tata-auto.careeris.in",
    fullName: "Priya Mehta",
    phone: "+91 98450 67890",
    avatarUrl: "",
    roleType: "EMPLOYER",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2026-01-05T09:30:00Z",
  },
  TRAINING_PROVIDER: {
    id: "user-tp-01",
    email: "principal@giti-pune.careeris.in",
    fullName: "Dr. Anand Joshi",
    phone: "+91 94220 54321",
    avatarUrl: "",
    roleType: "TRAINING_PROVIDER",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-12-15T08:00:00Z",
  },
  ITI_ADMIN: {
    id: "user-iti-01",
    email: "superintendent@iti-aundh.gov.in",
    fullName: "R. K. Shinde, ITI Superintendent",
    phone: "+91 94220 11223",
    avatarUrl: "",
    roleType: "ITI_ADMIN",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-12-15T08:00:00Z",
  },
  INSTRUCTOR: {
    id: "user-inst-01",
    email: "suresh.bms@iti-aundh.gov.in",
    fullName: "Suresh Gaikwad, Master Instructor",
    phone: "+91 94220 99887",
    avatarUrl: "",
    roleType: "INSTRUCTOR",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-12-20T08:00:00Z",
  },
  ASSESSOR: {
    id: "user-as-01",
    email: "lead.assessor@asdc.org.in",
    fullName: "Dr. Meenakshi Sundaram",
    phone: "+91 94440 12345",
    avatarUrl: "",
    roleType: "ASSESSOR",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2026-01-02T08:00:00Z",
  },
  STATE_ADMIN: {
    id: "user-sta-01",
    email: "director@dvet.maharashtra.gov.in",
    fullName: "Pravin More, State Director",
    phone: "+91 98200 11223",
    avatarUrl: "",
    roleType: "STATE_ADMIN",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-11-15T10:00:00Z",
  },
  PROGRAM_MANAGER: {
    id: "user-pm-01",
    email: "pm.strive@msde.gov.in",
    fullName: "Arun Varma, National Program Manager",
    phone: "+91 99100 44556",
    avatarUrl: "",
    roleType: "PROGRAM_MANAGER",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-12-05T11:00:00Z",
  },
  GOVERNMENT_ADMIN: {
    id: "user-gov-01",
    email: "director.skills@gov.careeris.in",
    fullName: "Rajeshwar Rao, IAS",
    phone: "+91 99100 88776",
    avatarUrl: "",
    roleType: "GOVERNMENT_ADMIN",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-11-01T10:00:00Z",
  },
  NATIONAL_GOVERNMENT: {
    id: "user-nat-01",
    email: "js.msde@gov.careeris.in",
    fullName: "Alok Kumar, Joint Secretary MSDE",
    phone: "+91 99100 11223",
    avatarUrl: "",
    roleType: "NATIONAL_GOVERNMENT",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-11-01T10:00:00Z",
  },
  STATE_GOVERNMENT: {
    id: "user-state-01",
    email: "sec.dvet@maharashtra.gov.in",
    fullName: "Vikram Deshmukh, Principal Secretary",
    phone: "+91 98200 44556",
    avatarUrl: "",
    roleType: "STATE_GOVERNMENT",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-11-15T10:00:00Z",
  },
  DISTRICT_ADMIN: {
    id: "user-dist-01",
    email: "dsdo.pune@skill.gov.careeris.in",
    fullName: "Sunita Deshmukh",
    phone: "+91 97660 33445",
    avatarUrl: "",
    roleType: "DISTRICT_ADMIN",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-12-01T11:00:00Z",
  },
  PROGRAM_ADMIN: {
    id: "user-prog-01",
    email: "dir.pmkvy@nsdcindia.org",
    fullName: "Sanjay Verma, Mission Director",
    phone: "+91 98111 22334",
    avatarUrl: "",
    roleType: "PROGRAM_ADMIN",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-12-05T11:00:00Z",
  },
  SCHEME_MANAGER: {
    id: "user-scheme-01",
    email: "manager.naps@dgt.gov.in",
    fullName: "Neha Sharma, Scheme Manager",
    phone: "+91 98100 55667",
    avatarUrl: "",
    roleType: "SCHEME_MANAGER",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-12-10T11:00:00Z",
  },
  SKILL_DEVELOPMENT_ADMIN: {
    id: "user-sda-01",
    email: "standards@ncvt.gov.in",
    fullName: "Dr. K. Ramanathan",
    phone: "+91 98400 66778",
    avatarUrl: "",
    roleType: "SKILL_DEVELOPMENT_ADMIN",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-12-15T11:00:00Z",
  },
  INDUSTRY_COUNCIL: {
    id: "user-ssc-01",
    email: "convenor@asdc.careeris.in",
    fullName: "Vikramjit Singh",
    phone: "+91 98110 99887",
    avatarUrl: "",
    roleType: "INDUSTRY_COUNCIL",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2026-01-02T14:00:00Z",
  },
  MONITORING_OFFICER: {
    id: "user-mon-01",
    email: "evaluator@niti.gov.in",
    fullName: "Deepa Narayan, Monitoring Lead",
    phone: "+91 99111 88990",
    avatarUrl: "",
    roleType: "MONITORING_OFFICER",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2026-01-05T14:00:00Z",
  },
  POLICY_ANALYST: {
    id: "user-pol-01",
    email: "analyst@msde.gov.in",
    fullName: "Rohan Kulkarni, Policy Analyst",
    phone: "+91 98222 33445",
    avatarUrl: "",
    roleType: "POLICY_ANALYST",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2026-01-10T14:00:00Z",
  },
  PLATFORM_ADMIN: {
    id: "user-admin-01",
    email: "superadmin@careeris.gov.in",
    fullName: "CareerIS National Admin",
    phone: "+91 98000 00001",
    avatarUrl: "",
    roleType: "PLATFORM_ADMIN",
    isActive: true,
    isEmailVerified: true,
    preferredLocale: "en",
    createdAt: "2025-10-01T00:00:00Z",
  },
};
