import { NextRequest, NextResponse } from "next/server";
import { EntityStatus, ProficiencyLevel } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/server/db/prisma";
import { resolveAuthContext } from "@/server/middleware/authContext";
import { resolveOrCreateSkill } from "@/server/services/skill/prismaSkillService";

const schema=z.object({title:z.string().trim().min(3).max(180),description:z.string().trim().max(3000).nullable().optional(),durationHours:z.coerce.number().int().positive(),level:z.nativeEnum(ProficiencyLevel),deliveryMode:z.string().trim().max(60).nullable().optional(),locationText:z.string().trim().max(160).nullable().optional(),eligibility:z.string().trim().max(500).nullable().optional(),capacity:z.coerce.number().int().min(0),status:z.nativeEnum(EntityStatus),skills:z.array(z.object({name:z.string().trim().min(1).max(80),targetLevel:z.nativeEnum(ProficiencyLevel)})).min(1)});
async function owned(userId:string,id:string){const account=await prisma.trainingProviderAccountProfile.findUnique({where:{userId}});if(!account?.trainingProviderId)return null;return prisma.course.findFirst({where:{id,trainingProviderId:account.trainingProviderId},include:{courseSkills:{include:{skill:true}},curriculums:{include:{modules:{include:{skills:{include:{skill:true}}}}}},enrollments:{include:{candidateProfile:{include:{user:{select:{fullName:true,email:true}}}}}}}})}
export async function GET(request:NextRequest,{params}:{params:{id:string}}){try{const auth=resolveAuthContext(request);if(auth.userRole!=="TRAINING_PROVIDER")return NextResponse.json({error:"Training-provider account required"},{status:403});const course=await owned(auth.userId,params.id);return course?NextResponse.json({course}):NextResponse.json({error:"Course not found"},{status:404})}catch(error){const message=error instanceof Error?error.message:"Could not load course";return NextResponse.json({error:message},{status:message==="Authentication required"?401:500})}}
export async function PATCH(request:NextRequest,{params}:{params:{id:string}}){try{const auth=resolveAuthContext(request);if(auth.userRole!=="TRAINING_PROVIDER")return NextResponse.json({error:"Training-provider account required"},{status:403});const current=await owned(auth.userId,params.id);if(!current)return NextResponse.json({error:"Course not found"},{status:404});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Please check the course details."},{status:400});const course=await prisma.$transaction(async tx=>{await tx.course.update({where:{id:current.id},data:{title:parsed.data.title,description:parsed.data.description||null,durationHours:parsed.data.durationHours,level:parsed.data.level,deliveryMode:parsed.data.deliveryMode||null,locationText:parsed.data.locationText||null,eligibility:parsed.data.eligibility||null,capacity:parsed.data.capacity,status:parsed.data.status,healthScore:null}});await tx.courseSkill.deleteMany({where:{courseId:current.id}});const linked=[];for(const item of parsed.data.skills){const skill=await resolveOrCreateSkill(item.name,tx);linked.push(skill);await tx.courseSkill.create({data:{courseId:current.id,skillId:skill.id,targetLevel:item.targetLevel}});}if(parsed.data.status==="ACTIVE"){const source=await tx.dataSource.create({data:{name:`CAREERIS course capacity ${current.id}`,sourceType:"TRAINING_DATA",timePeriod:new Date().toISOString().slice(0,10),geographyScope:parsed.data.locationText||parsed.data.deliveryMode||"UNSPECIFIED",confidence:null,methodology:"Published capacity submitted by a registered CAREERIS training provider",version:"1"}});for(const skill of linked)await tx.supplySignal.create({data:{dataSourceId:source.id,skillId:skill.id,certifiedTrainees:parsed.data.capacity,sourceEntity:"COURSE",sourceEntityId:current.id,provenance:{courseId:current.id,providerId:current.trainingProviderId}}});}await tx.auditLog.create({data:{userId:auth.userId,action:current.status!==parsed.data.status?"COURSE_PUBLICATION_CHANGE":"COURSE_UPDATE",entity:"Course",entityId:current.id,newValue:{status:parsed.data.status,capacity:parsed.data.capacity}}});return tx.course.findUniqueOrThrow({where:{id:current.id},include:{courseSkills:{include:{skill:true}}}})});return NextResponse.json({course});}catch(error){const message=error instanceof Error?error.message:"Could not update course";return NextResponse.json({error:message},{status:message==="Authentication required"?401:500})}}
export async function DELETE(request:NextRequest,{params}:{params:{id:string}}){try{const auth=resolveAuthContext(request);if(auth.userRole!=="TRAINING_PROVIDER")return NextResponse.json({error:"Training-provider account required"},{status:403});const current=await owned(auth.userId,params.id);if(!current)return NextResponse.json({error:"Course not found"},{status:404});await prisma.$transaction([prisma.course.update({where:{id:current.id},data:{status:"ARCHIVED"}}),prisma.auditLog.create({data:{userId:auth.userId,action:"COURSE_ARCHIVE",entity:"Course",entityId:current.id}})]);return NextResponse.json({success:true});}catch(error){const message=error instanceof Error?error.message:"Could not archive course";return NextResponse.json({error:message},{status:message==="Authentication required"?401:500})}}
