import { State, District, IndustrialCluster } from "@/types";

export const INDIA_STATES_UT: State[] = [
  // Pilot Reference Geography
  {
    id: "state-mh",
    countryId: "country-in",
    code: "MH",
    name: "Maharashtra",
    isUT: false,
    isPilotArea: true, // SIH Pilot Reference Geography
    capital: "Mumbai",
    regionCount: 6,
    districtCount: 36,
  },
  // Other States & UTs (Pan-India Generic Model)
  {
    id: "state-ka",
    countryId: "country-in",
    code: "KA",
    name: "Karnataka",
    isUT: false,
    isPilotArea: false,
    capital: "Bengaluru",
    regionCount: 4,
    districtCount: 31,
  },
  {
    id: "state-tn",
    countryId: "country-in",
    code: "TN",
    name: "Tamil Nadu",
    isUT: false,
    isPilotArea: false,
    capital: "Chennai",
    regionCount: 4,
    districtCount: 38,
  },
  {
    id: "state-gj",
    countryId: "country-in",
    code: "GJ",
    name: "Gujarat",
    isUT: false,
    isPilotArea: false,
    capital: "Gandhinagar",
    regionCount: 4,
    districtCount: 33,
  },
  {
    id: "state-ts",
    countryId: "country-in",
    code: "TS",
    name: "Telangana",
    isUT: false,
    isPilotArea: false,
    capital: "Hyderabad",
    regionCount: 3,
    districtCount: 33,
  },
  {
    id: "state-up",
    countryId: "country-in",
    code: "UP",
    name: "Uttar Pradesh",
    isUT: false,
    isPilotArea: false,
    capital: "Lucknow",
    regionCount: 18,
    districtCount: 75,
  },
  {
    id: "state-dl",
    countryId: "country-in",
    code: "DL",
    name: "Delhi",
    isUT: true,
    isPilotArea: false,
    capital: "New Delhi",
    regionCount: 1,
    districtCount: 11,
  },
  {
    id: "state-hr",
    countryId: "country-in",
    code: "HR",
    name: "Haryana",
    isUT: false,
    isPilotArea: false,
    capital: "Chandigarh",
    regionCount: 6,
    districtCount: 22,
  },
  {
    id: "state-rj",
    countryId: "country-in",
    code: "RJ",
    name: "Rajasthan",
    isUT: false,
    isPilotArea: false,
    capital: "Jaipur",
    regionCount: 7,
    districtCount: 50,
  },
  {
    id: "state-wb",
    countryId: "country-in",
    code: "WB",
    name: "West Bengal",
    isUT: false,
    isPilotArea: false,
    capital: "Kolkata",
    regionCount: 5,
    districtCount: 23,
  },
  {
    id: "state-ap",
    countryId: "country-in",
    code: "AP",
    name: "Andhra Pradesh",
    isUT: false,
    isPilotArea: false,
    capital: "Amaravati",
    regionCount: 3,
    districtCount: 26,
  },
  {
    id: "state-kl",
    countryId: "country-in",
    code: "KL",
    name: "Kerala",
    isUT: false,
    isPilotArea: false,
    capital: "Thiruvananthapuram",
    regionCount: 3,
    districtCount: 14,
  },
  {
    id: "state-mp",
    countryId: "country-in",
    code: "MP",
    name: "Madhya Pradesh",
    isUT: false,
    isPilotArea: false,
    capital: "Bhopal",
    regionCount: 10,
    districtCount: 55,
  },
  {
    id: "state-or",
    countryId: "country-in",
    code: "OD",
    name: "Odisha",
    isUT: false,
    isPilotArea: false,
    capital: "Bhubaneswar",
    regionCount: 3,
    districtCount: 30,
  },
  {
    id: "state-pb",
    countryId: "country-in",
    code: "PB",
    name: "Punjab",
    isUT: false,
    isPilotArea: false,
    capital: "Chandigarh",
    regionCount: 5,
    districtCount: 23,
  },
  {
    id: "state-as",
    countryId: "country-in",
    code: "AS",
    name: "Assam",
    isUT: false,
    isPilotArea: false,
    capital: "Dispur",
    regionCount: 5,
    districtCount: 35,
  }
];

export const INDIA_DISTRICTS: District[] = [
  // Maharashtra Districts (Pilot reference)
  {
    id: "dist-mh-pun",
    stateId: "state-mh",
    code: "MH-PUN",
    name: "Pune",
    headquarters: "Pune",
    stateName: "Maharashtra",
    industrialClustersCount: 4,
  },
  {
    id: "dist-mh-mum",
    stateId: "state-mh",
    code: "MH-MUM",
    name: "Mumbai Suburban",
    headquarters: "Bandra",
    stateName: "Maharashtra",
    industrialClustersCount: 3,
  },
  {
    id: "dist-mh-ngp",
    stateId: "state-mh",
    code: "MH-NGP",
    name: "Nagpur",
    headquarters: "Nagpur",
    stateName: "Maharashtra",
    industrialClustersCount: 2,
  },
  {
    id: "dist-mh-aur",
    stateId: "state-mh",
    code: "MH-AUR",
    name: "Chhatrapati Sambhajinagar",
    headquarters: "Sambhajinagar",
    stateName: "Maharashtra",
    industrialClustersCount: 2,
  },
  {
    id: "dist-mh-nsk",
    stateId: "state-mh",
    code: "MH-NSK",
    name: "Nashik",
    headquarters: "Nashik",
    stateName: "Maharashtra",
    industrialClustersCount: 2,
  },
  {
    id: "dist-mh-tha",
    stateId: "state-mh",
    code: "MH-THA",
    name: "Thane",
    headquarters: "Thane",
    stateName: "Maharashtra",
    industrialClustersCount: 3,
  },
  // Karnataka Districts
  {
    id: "dist-ka-blr",
    stateId: "state-ka",
    code: "KA-BLR",
    name: "Bengaluru Urban",
    headquarters: "Bengaluru",
    stateName: "Karnataka",
    industrialClustersCount: 5,
  },
  {
    id: "dist-ka-mys",
    stateId: "state-ka",
    code: "KA-MYS",
    name: "Mysuru",
    headquarters: "Mysuru",
    stateName: "Karnataka",
    industrialClustersCount: 2,
  },
  // Tamil Nadu Districts
  {
    id: "dist-tn-chn",
    stateId: "state-tn",
    code: "TN-CHN",
    name: "Chennai",
    headquarters: "Chennai",
    stateName: "Tamil Nadu",
    industrialClustersCount: 4,
  },
  {
    id: "dist-tn-cbe",
    stateId: "state-tn",
    code: "TN-CBE",
    name: "Coimbatore",
    headquarters: "Coimbatore",
    stateName: "Tamil Nadu",
    industrialClustersCount: 3,
  },
  // Gujarat Districts
  {
    id: "dist-gj-ahd",
    stateId: "state-gj",
    code: "GJ-AHD",
    name: "Ahmedabad",
    headquarters: "Ahmedabad",
    stateName: "Gujarat",
    industrialClustersCount: 4,
  },
  {
    id: "dist-gj-srt",
    stateId: "state-gj",
    code: "GJ-SRT",
    name: "Surat",
    headquarters: "Surat",
    stateName: "Gujarat",
    industrialClustersCount: 3,
  },
  // Telangana Districts
  {
    id: "dist-ts-hyd",
    stateId: "state-ts",
    code: "TS-HYD",
    name: "Hyderabad",
    headquarters: "Hyderabad",
    stateName: "Telangana",
    industrialClustersCount: 4,
  },
  // Uttar Pradesh Districts
  {
    id: "dist-up-gbn",
    stateId: "state-up",
    code: "UP-GBN",
    name: "Gautam Buddha Nagar (Noida)",
    headquarters: "Noida",
    stateName: "Uttar Pradesh",
    industrialClustersCount: 4,
  },
  // Delhi District
  {
    id: "dist-dl-new",
    stateId: "state-dl",
    code: "DL-NEW",
    name: "New Delhi",
    headquarters: "New Delhi",
    stateName: "Delhi",
    industrialClustersCount: 2,
  },
  // Haryana District
  {
    id: "dist-hr-ggn",
    stateId: "state-hr",
    code: "HR-GGN",
    name: "Gurugram",
    headquarters: "Gurugram",
    stateName: "Haryana",
    industrialClustersCount: 4,
  }
];

export const INDUSTRIAL_CLUSTERS: IndustrialCluster[] = [
  {
    id: "cluster-chakan",
    districtId: "dist-mh-pun",
    code: "MH-PUN-CHAKAN",
    name: "Chakan Automotive, EV & Robotics Corridor",
    sectorFocus: ["Automotive & EV", "Robotics", "Heavy Engineering"],
    activeUnits: 840,
  },
  {
    id: "cluster-hinjawadi",
    districtId: "dist-mh-pun",
    code: "MH-PUN-HINJ",
    name: "Rajiv Gandhi Infotech Park (Hinjawadi)",
    sectorFocus: ["IT & AI", "Semiconductors", "Cloud & Cybersecurity"],
    activeUnits: 420,
  },
  {
    id: "cluster-shendra-bidkin",
    districtId: "dist-mh-aur",
    code: "MH-AUR-AURIC",
    name: "AURIC Shendra-Bidkin Smart City Node",
    sectorFocus: ["Advanced Manufacturing", "Defence", "Electronics"],
    activeUnits: 190,
  },
  {
    id: "cluster-ecity",
    districtId: "dist-ka-blr",
    code: "KA-BLR-ECITY",
    name: "Electronic City & Sarjapur Tech Hub",
    sectorFocus: ["IT & AI", "IoT & Embedded Systems", "FinTech"],
    activeUnits: 650,
  },
  {
    id: "cluster-sriperumbudur",
    districtId: "dist-tn-chn",
    code: "TN-CHN-SRIP",
    name: "Sriperumbudur - Oragadam Industrial Belt",
    sectorFocus: ["Automotive & EV", "Electronics Manufacturing", "Solar Energy"],
    activeUnits: 510,
  },
  {
    id: "cluster-sanand",
    districtId: "dist-gj-ahd",
    code: "GJ-AHD-SND",
    name: "Sanand Auto & Semiconductor Park",
    sectorFocus: ["Semiconductor Assembly", "Automotive", "Precision Engineering"],
    activeUnits: 340,
  },
  {
    id: "cluster-hitec-city",
    districtId: "dist-ts-hyd",
    code: "TS-HYD-HITEC",
    name: "HITEC City & Genome Valley",
    sectorFocus: ["Life Sciences & Pharma", "IT & AI", "Aerospace"],
    activeUnits: 580,
  },
  {
    id: "cluster-noida-tech",
    districtId: "dist-up-gbn",
    code: "UP-GBN-NOIDA",
    name: "Noida Electronics & Mobile Manufacturing Corridor",
    sectorFocus: ["Electronics Hardware", "Software Services", "EV Components"],
    activeUnits: 490,
  }
];
