-- Initial Migration Snapshot for CareerIS PostgreSQL Database Schema
-- Supports RBAC, Geography, Skills Graph, Candidates, Jobs, Assessments, Courses, Government, and Audit

-- Create Enums
CREATE TYPE "UserRoleType" AS ENUM ('CANDIDATE', 'EMPLOYER', 'TRAINING_PROVIDER', 'GOVERNMENT_ADMIN', 'DISTRICT_ADMIN', 'INDUSTRY_COUNCIL', 'PLATFORM_ADMIN');
CREATE TYPE "EntityStatus" AS ENUM ('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'INACTIVE', 'ARCHIVED', 'SUSPENDED');
CREATE TYPE "ProficiencyLevel" AS ENUM ('FOUNDATIONAL', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', 'MASTER');
CREATE TYPE "SkillRelationshipType" AS ENUM ('PREREQUISITE', 'RELATED', 'SPECIALIZATION_OF', 'SYNONYMOUS_WITH', 'COMMONLY_PAIRED_WITH', 'REPLACES');
CREATE TYPE "JobType" AS ENUM ('FULL_TIME', 'PART_TIME', 'APPRENTICESHIP', 'INTERNSHIP', 'CONTRACT', 'REMOTE', 'HYBRID');
CREATE TYPE "ApplicationStatus" AS ENUM ('SUBMITTED', 'SCREENING', 'ASSESSMENT', 'INTERVIEW_SCHEDULED', 'OFFER_EXTENDED', 'PLACED', 'REJECTED', 'WITHDRAWN');
CREATE TYPE "EvidenceVerificationStatus" AS ENUM ('UNVERIFIED', 'SELF_ATTESTED', 'ASSESSMENT_VERIFIED', 'INSTITUTE_VERIFIED', 'EMPLOYER_VERIFIED', 'AI_PROCTORED_VERIFIED', 'THIRD_PARTY_CREDENTIALED');

-- Create Tables
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL UNIQUE,
    "fullName" TEXT NOT NULL,
    "roleType" "UserRoleType" NOT NULL DEFAULT 'CANDIDATE',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "Country" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "code" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "State" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "countryId" TEXT NOT NULL,
    "code" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "isUT" BOOLEAN NOT NULL DEFAULT false,
    "isPilotArea" BOOLEAN NOT NULL DEFAULT false,
    "capital" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE CASCADE
);

CREATE TABLE "District" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "stateId" TEXT NOT NULL,
    "code" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "headquarters" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("stateId") REFERENCES "State"("id") ON DELETE CASCADE
);

CREATE TABLE "SkillCategory" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "code" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL UNIQUE
);

CREATE TABLE "Skill" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "categoryId" TEXT NOT NULL,
    "code" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "isEmerging" BOOLEAN NOT NULL DEFAULT false,
    "isGreenSkill" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("categoryId") REFERENCES "SkillCategory"("id") ON DELETE CASCADE
);

CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "entity" TEXT NOT NULL,
    "entityId" TEXT,
    "details" JSONB,
    "ipAddress" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create Indexes
CREATE INDEX "Skill_category_idx" ON "Skill"("categoryId");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
