import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/server/db/prisma";
import { resolveAuthContext } from "@/server/middleware/authContext";

async function ownedCourse(userId:string,id:string){const account=await prisma.trainingProviderAccountProfile.findUnique({where:{userId}});if(!account?.trainingProviderId)return null;return prisma.course.findFirst({where:{id,trainingProviderId:account.trainingProviderId},include:{courseSkills:{include:{skill:true}}}})}
export async function GET(request:NextRequest,{params}:{params:{id:string}}){try{const auth=resolveAuthContext(request);if(auth.userRole!=="TRAINING_PROVIDER")return NextResponse.json({error:"Training-provider account required"},{status:403});const course=await ownedCourse(auth.userId,params.id);if(!course)return NextResponse.json({error:"Course not found"},{status:404});const enrollments=await prisma.courseEnrollment.findMany({where:{courseId:course.id},orderBy:{enrolledAt:"desc"},include:{candidateProfile:{include:{user:{select:{fullName:true,email:true}}}}}});return NextResponse.json({course,enrollments});}catch(error){const message=error instanceof Error?error.message:"Could not load enrollments";return NextResponse.json({error:message},{status:message==="Authentication required"?401:500})}}
const schema=z.object({enrollmentId:z.string().uuid(),status:z.enum(["ENROLLED","IN_PROGRESS","COMPLETED","WITHDRAWN"]),completionEvidenceUrl:z.string().url().nullable().optional()});
export async function PATCH(request:NextRequest,{params}:{params:{id:string}}){try{const auth=resolveAuthContext(request);if(auth.userRole!=="TRAINING_PROVIDER")return NextResponse.json({error:"Training-provider account required"},{status:403});const course=await ownedCourse(auth.userId,params.id);if(!course)return NextResponse.json({error:"Course not found"},{status:404});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invalid enrollment update"},{status:400});const current=await prisma.courseEnrollment.findFirst({where:{id:parsed.data.enrollmentId,courseId:course.id}});if(!current)return NextResponse.json({error:"Enrollment not found"},{status:404});const completed=parsed.data.status==="COMPLETED";const enrollment=await prisma.$transaction(async tx=>{const updated=await tx.courseEnrollment.update({where:{id:current.id},data:{status:parsed.data.status,completedAt:completed?new Date():null,providerConfirmedAt:completed?new Date():null,completionEvidenceUrl:parsed.data.completionEvidenceUrl||null}});if(completed){for(const item of course.courseSkills)await tx.candidateDeclaredSkill.updateMany({where:{candidateProfileId:current.candidateProfileId,skillId:item.skillId},data:{trainingStatus:"COMPLETED",trainingCompletedAt:new Date()}});}await tx.auditLog.create({data:{userId:auth.userId,action:"ENROLLMENT_STATUS_CHANGE",entity:"CourseEnrollment",entityId:current.id,oldValue:{status:current.status},newValue:{status:parsed.data.status}}});return updated;});return NextResponse.json({enrollment});}catch(error){const message=error instanceof Error?error.message:"Could not update enrollment";return NextResponse.json({error:message},{status:message==="Authentication required"?401:500})}}
