"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { Briefcase,Plus,Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";

export default function EmployerJobsPage(){const [jobs,setJobs]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{fetch("/api/jobs?mine=1",{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setJobs(b.jobs||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);return <main className="mx-auto max-w-5xl space-y-6 pb-16"><header className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Company jobs</p><h1 className="mt-1 text-3xl font-extrabold">Your published jobs</h1><p className="mt-2 text-sm text-muted-foreground">Only jobs published by this company account are shown.</p></div><Button asChild><Link href="/employer/jobs/new"><Plus className="mr-2 h-4 w-4"/>Publish job</Link></Button></header>{error&&<div className="rounded-xl border border-red-500/30 p-4 text-sm text-red-600">{error}</div>}{loading?<p className="text-sm text-muted-foreground">Loading…</p>:jobs.length===0?<Card><CardContent className="p-10 text-center"><Briefcase className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 text-sm">No jobs published by this company.</p></CardContent></Card>:<div className="space-y-3">{jobs.map(job=><Card key={job.id}><CardContent className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><h2 className="font-bold">{job.title}</h2><Badge>{job.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{job.location||"No location"} · {job.openPositions} opening(s)</p><div className="mt-2 flex flex-wrap gap-1">{job.requirements.map((r:any)=><Badge key={`${r.name}-${r.proficiency}`} variant="secondary">{r.name} · {r.proficiency}</Badge>)}</div></div><Button asChild variant="outline"><Link href={`/employer/jobs/${job.id}/pipeline`}><Users className="mr-2 h-4 w-4"/>{job.applications} applicant(s)</Link></Button></CardContent></Card>)}</div>}</main>}
