"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { BrainCircuit, Plus, Save, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Skill = { name: string; proficiency: string; verificationStatus?: string; assessedScore?: number | null; assessmentPassed?: boolean | null };
const levels = ["FOUNDATIONAL", "INTERMEDIATE", "ADVANCED", "EXPERT", "MASTER"];

export default function CandidateProfilePage() {
  const [form, setForm] = useState({ fullName: "", email: "", location: "", education: "", qualification: "", experience: "", targetRole: "", headline: "", skills: [] as Skill[] });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = useCallback(async () => { try { const response = await fetch("/api/candidate/profile", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); const p = body.profile; setForm({ fullName: p.user.fullName, email: p.user.email, location: p.location || "", education: p.educationSummary || "", qualification: p.qualification || "", experience: p.experienceSummary || "", targetRole: p.targetRole || "", headline: p.headline || "", skills: p.declaredSkills.map((s: any) => ({ name: s.name, proficiency: s.claimedProficiency, verificationStatus: s.verificationStatus, assessedScore: s.assessedScore, assessmentPassed: s.assessmentPassed })) }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load profile"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  function updateSkill(index: number, changes: Partial<Skill>) { setForm((current) => ({ ...current, skills: current.skills.map((skill, i) => i === index ? { ...skill, ...changes } : skill) })); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); setSuccess(""); try { const response = await fetch("/api/candidate/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setSuccess("Profile saved to CAREERIS."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save profile"); } finally { setSaving(false); } }
  if (loading) return <p className="text-sm text-muted-foreground">Loading your profile…</p>;
  return <main className="mx-auto max-w-4xl space-y-6 pb-16"><header><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Candidate</p><h1 className="mt-1 text-3xl font-extrabold">My profile</h1><p className="mt-2 text-sm text-muted-foreground">Your details and self-declared skills are stored in your CAREERIS account.</p></header>
    {error && <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-4 text-sm text-red-600">{error}</div>}{success && <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/5 p-4 text-sm text-emerald-700">{success}</div>}
    <Card><CardHeader><CardTitle>Edit profile</CardTitle></CardHeader><CardContent><form onSubmit={save} className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Name<Input className="mt-1" required value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})}/></label><label className="text-sm font-semibold">Email<Input className="mt-1" disabled value={form.email}/></label><label className="text-sm font-semibold">Location<Input className="mt-1" value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/></label><label className="text-sm font-semibold">Education<Input className="mt-1" value={form.education} onChange={(e)=>setForm({...form,education:e.target.value})}/></label><label className="text-sm font-semibold">Qualification<Input className="mt-1" value={form.qualification} onChange={(e)=>setForm({...form,qualification:e.target.value})}/></label><label className="text-sm font-semibold">Target career / role<Input className="mt-1" value={form.targetRole} onChange={(e)=>setForm({...form,targetRole:e.target.value})}/></label></div><label className="text-sm font-semibold">Experience<Textarea className="mt-1" rows={3} placeholder="Example: 2 years as a data analyst" value={form.experience} onChange={(e)=>setForm({...form,experience:e.target.value})}/></label>
      <section className="space-y-3"><div className="flex items-center justify-between"><div><h2 className="font-bold">Declared skills</h2><p className="text-xs text-muted-foreground">A declaration is not verified evidence. Passing assessments and verified projects are tracked separately.</p></div><Button type="button" variant="outline" size="sm" onClick={()=>setForm({...form,skills:[...form.skills,{name:"",proficiency:"FOUNDATIONAL"}]})}><Plus className="mr-1 h-4 w-4"/>Add skill</Button></div>{form.skills.length===0&&<div className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No declared skills.</div>}{form.skills.map((skill,index)=><div key={index} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-[1fr_180px_auto]"><Input required placeholder="Skill name" value={skill.name} onChange={(e)=>updateSkill(index,{name:e.target.value})}/><select className="rounded-md border bg-background px-3 text-sm" value={skill.proficiency} onChange={(e)=>updateSkill(index,{proficiency:e.target.value})}>{levels.map(level=><option key={level}>{level}</option>)}</select><Button type="button" size="icon" variant="ghost" aria-label="Remove skill" onClick={()=>setForm({...form,skills:form.skills.filter((_,i)=>i!==index)})}><Trash2 className="h-4 w-4"/></Button>{skill.assessedScore!=null&&<p className="col-span-full text-xs text-muted-foreground">Latest assessment: {Math.round(skill.assessedScore)}% · {skill.assessmentPassed ? "PASSED" : "FAILED"}</p>}</div>)}</section><Button disabled={saving} type="submit"><Save className="mr-2 h-4 w-4"/>{saving?"Saving…":"Save profile"}</Button></form></CardContent></Card>
    <Card className="border-primary/30 bg-primary/5"><CardContent className="flex flex-col items-start justify-between gap-4 p-6 sm:flex-row sm:items-center"><div><h2 className="flex items-center gap-2 font-bold"><BrainCircuit className="h-5 w-5 text-primary"/>Assess declared skills</h2><p className="mt-1 text-xs text-muted-foreground">A failed assessment remains a skill gap and does not satisfy job requirements.</p></div><Button asChild><Link href="/candidate/quiz">Start diagnostic</Link></Button></CardContent></Card>
  </main>;
}
