import { randomUUID } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { EntityStatus, ProficiencyLevel } from "@prisma/client";
import { z } from "zod";
import { prisma } from "@/server/db/prisma";
import { resolveAuthContext } from "@/server/middleware/authContext";
import { resolveOrCreateSkill } from "@/server/services/skill/prismaSkillService";

const schema=z.object({title:z.string().trim().min(3).max(180),description:z.string().trim().max(3000).nullable().optional(),durationHours:z.coerce.number().int().positive().max(20000),level:z.nativeEnum(ProficiencyLevel),deliveryMode:z.string().trim().max(60).nullable().optional(),locationText:z.string().trim().max(160).nullable().optional(),eligibility:z.string().trim().max(500).nullable().optional(),sourceUrl:z.string().url().nullable().optional(),enrollmentUrl:z.string().url().nullable().optional(),evidenceNote:z.string().trim().max(500).nullable().optional(),capacity:z.coerce.number().int().min(0).max(100000),status:z.nativeEnum(EntityStatus).default(EntityStatus.DRAFT),skills:z.array(z.object({name:z.string().trim().min(1).max(80),targetLevel:z.nativeEnum(ProficiencyLevel)})).min(1).max(50)});
async function providerFor(userId:string){return prisma.trainingProviderAccountProfile.findUnique({where:{userId},select:{trainingProviderId:true}})}

export async function GET(request:NextRequest){try{const auth=resolveAuthContext(request);if(auth.userRole!=="TRAINING_PROVIDER")return NextResponse.json({error:"Training-provider account required"},{status:403});const account=await providerFor(auth.userId);if(!account?.trainingProviderId)return NextResponse.json({courses:[]});const courses=await prisma.course.findMany({where:{trainingProviderId:account.trainingProviderId},orderBy:{createdAt:"desc"},include:{courseSkills:{include:{skill:true}},curriculums:{include:{modules:{include:{skills:{include:{skill:true}}}}}},_count:{select:{enrollments:true}}}});return NextResponse.json({courses});}catch(error){const message=error instanceof Error?error.message:"Could not load courses";return NextResponse.json({error:message},{status:message==="Authentication required"?401:500})}}

export async function POST(request:NextRequest){try{const auth=resolveAuthContext(request);if(auth.userRole!=="TRAINING_PROVIDER")return NextResponse.json({error:"Training-provider account required"},{status:403});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Please check the course details.",issues:parsed.error.flatten()},{status:400});const account=await providerFor(auth.userId);if(!account?.trainingProviderId)return NextResponse.json({error:"Provider record not found"},{status:404});const course=await prisma.$transaction(async tx=>{const created=await tx.course.create({data:{trainingProviderId:account.trainingProviderId!,code:`COURSE-${randomUUID()}`,title:parsed.data.title,description:parsed.data.description||null,durationHours:parsed.data.durationHours,level:parsed.data.level,deliveryMode:parsed.data.deliveryMode||null,locationText:parsed.data.locationText||null,eligibility:parsed.data.eligibility||null,sourceUrl:parsed.data.sourceUrl||null,enrollmentUrl:parsed.data.enrollmentUrl||null,evidenceNote:parsed.data.evidenceNote||null,capacity:parsed.data.capacity,status:parsed.data.status,healthScore:null}});for(const item of parsed.data.skills){const skill=await resolveOrCreateSkill(item.name,tx);await tx.courseSkill.create({data:{courseId:created.id,skillId:skill.id,targetLevel:item.targetLevel}});}await tx.auditLog.create({data:{userId:auth.userId,action:"COURSE_CREATE",entity:"Course",entityId:created.id,newValue:{status:created.status,capacity:created.capacity}}});return tx.course.findUniqueOrThrow({where:{id:created.id},include:{courseSkills:{include:{skill:true}}}})});return NextResponse.json({course},{status:201});}catch(error){const message=error instanceof Error?error.message:"Could not create course";return NextResponse.json({error:message},{status:message==="Authentication required"?401:500})}}
